# Generated by Django 5.0.3 on 2024-07-14 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ecommerce', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_has_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prod_has_category1', to='my_ecommerce.category'),
        ),
    ]
