# Generated by Django 5.0.3 on 2024-07-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ecommerce', '0004_order_created_by_order_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
